name: Image build

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    paths:
      - '**.php'
      - 'composer.*'
      - 'config/**'
      - '.github/**'
      - 'Procfile'
      - 'project.toml'
  pull_request:
    branches: [ "main" ]

env:
  DESCRIPTION: "Word press Heroku App Image https://kubectl.blog"
  IMAGE_NAME: "ghcr.io/${{ github.repository_owner }}/kubectl.blog"
  BUILDER: "heroku/builder-classic:22"
jobs:
  pack-build:
    name: Pack Build and Publish!
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v1
    - id: setup-tools
      uses: buildpacks/github-actions/setup-tools@v5.1.0
    - id: setup-pack
      uses: buildpacks/github-actions/setup-pack@v5.1.0
    - name: Docker registry login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set build environment
      run: |
        year=$(date +%Y);
        day=$(date +%j);
        ref="${GITHUB_REF#refs/*/}";
        echo "REF=$ref" >> $GITHUB_ENV;
        tag="${GITHUB_REF#tags/*/}";
        [[ $tag == '' ]] || tag="${year}.${day}.${{ github.run_number }}";
        echo "TAG=$tag" >> $GITHUB_ENV;
    - name: Build Image with pack
      run: |
        [[ ! -z  $(yq e '. | keys' Procfile | cut -c 3- | grep bash) ]] \
        || echo 'bash: bash -l' >> Procfile
        pack build "$IMAGE_NAME:$TAG" \
          --builder $BUILDER \
          --descriptor project.toml \
          --workspace /app;
    - name: Tag Docker image to ref
      run: |
        docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:$REF
    - name: Docker push
      run: |
        docker push $IMAGE_NAME:$TAG
        docker push $IMAGE_NAME:$REF
